name: Build and Publish to GitHub Packages

on:
  push:
    branches:
      - main
    # タグpushでpublishしたい場合はコメントアウト解除
    # tags:
    #   - 'v*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: api-service-template
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Configure npm for GitHub Packages
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      - name: Publish package to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
